-- Migration to synchronize schema with defined requirements
-- Auto-generated by Agent

-- 1. Create missing tables

-- Products
CREATE TABLE IF NOT EXISTS public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
  name text NOT NULL,
  description text,
  price numeric DEFAULT 0,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);

-- Deal Items
CREATE TABLE IF NOT EXISTS public.deal_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  deal_id uuid,
  product_id uuid,
  quantity integer DEFAULT 1,
  unit_price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT deal_items_pkey PRIMARY KEY (id),
  CONSTRAINT deal_items_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT deal_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);

-- Custom Field Definitions
CREATE TABLE IF NOT EXISTS public.custom_field_definitions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['text'::text, 'number'::text, 'date'::text, 'select'::text, 'url'::text])),
  options text[],
  show_in_card boolean DEFAULT false,
  position integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT custom_field_definitions_pkey PRIMARY KEY (id),
  CONSTRAINT custom_field_definitions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);

-- 2. Alter existing tables

-- Add tenant_id to cold_leads
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'cold_leads' AND column_name = 'tenant_id') THEN
        ALTER TABLE public.cold_leads ADD COLUMN tenant_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid;
        ALTER TABLE public.cold_leads ADD CONSTRAINT cold_leads_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
END $$;

-- Add custom_values to deals
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'deals' AND column_name = 'custom_values') THEN
        ALTER TABLE public.deals ADD COLUMN custom_values jsonb DEFAULT '{}'::jsonb;
    END IF;
END $$;

-- 3. Security (RLS) & Performance

-- Enable RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deal_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_field_definitions ENABLE ROW LEVEL SECURITY;

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_products_tenant_id ON public.products(tenant_id);
CREATE INDEX IF NOT EXISTS idx_deal_items_deal_id ON public.deal_items(deal_id);
CREATE INDEX IF NOT EXISTS idx_deal_items_product_id ON public.deal_items(product_id);
CREATE INDEX IF NOT EXISTS idx_custom_field_definitions_tenant_id ON public.custom_field_definitions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_cold_leads_tenant_id ON public.cold_leads(tenant_id);
