-- Modulo Clinica Veterinaria — Fase 4: Agenda de Atendimentos.
-- Novo nucleo operacional vet: o "atendimento" (consulta/banho/vacina/retorno)
-- com dia, hora, profissional e status — substitui o "deal" de vendas no fluxo
-- da clinica. Acompanha o catalogo de servicos (base do agendamento e do
-- futuro financeiro).

-- ============================================================
-- 1. CATALOGO DE SERVICOS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.vet_services (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id    uuid NOT NULL,
  name         text NOT NULL,
  category     text,                    -- consulta, banho_tosa, vacina, exame, cirurgia, retorno
  price        numeric DEFAULT 0,
  duration_min integer DEFAULT 30,
  active       boolean DEFAULT true,
  created_at   timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_vet_services_tenant ON public.vet_services(tenant_id);

-- ============================================================
-- 2. ATENDIMENTOS (agenda)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.appointments (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL,
  pet_id          uuid REFERENCES public.pets(id) ON DELETE SET NULL,
  contact_id      uuid REFERENCES public.contacts(id) ON DELETE SET NULL,  -- tutor
  service_id      bigint REFERENCES public.vet_services(id) ON DELETE SET NULL,
  service_name    text,                  -- snapshot do servico no momento do agendamento
  professional_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,  -- veterinario
  starts_at       timestamptz NOT NULL,
  duration_min    integer DEFAULT 30,
  status          text DEFAULT 'agendado',  -- agendado, confirmado, atendido, faltou, cancelado
  price           numeric DEFAULT 0,
  notes           text,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_appointments_tenant  ON public.appointments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_appointments_starts  ON public.appointments(tenant_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_appointments_pet     ON public.appointments(pet_id);
CREATE INDEX IF NOT EXISTS idx_appointments_contact ON public.appointments(contact_id);

-- ============================================================
-- 3. RLS — isolamento por tenant (padrao do CRM)
-- ============================================================
ALTER TABLE public.vet_services  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS vet_services_tenant_isolation ON public.vet_services;
CREATE POLICY vet_services_tenant_isolation ON public.vet_services
  FOR ALL
  USING (tenant_id = (SELECT current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT current_tenant_id()));

DROP POLICY IF EXISTS appointments_tenant_isolation ON public.appointments;
CREATE POLICY appointments_tenant_isolation ON public.appointments
  FOR ALL
  USING (tenant_id = (SELECT current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT current_tenant_id()));
